In [1]:
import pandas as pd

In [66]:
# reading the data
orders_raw = pd.read_excel('data/Muesli Project raw data.xlsx', sheet_name='Orders')
orders_raw.head()

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18
0,Index,Order ID,Order Date,Ship Mode,Customer ID,Customer Name,Origin Channel,Country/Region,City,State,Postal Code,Region,Category,Sub-Category,Product ID,Sales,Quantity,Discount,Profit
1,27,CA-2019-121755,2019-01-16 00:00:00,Second Class,EH-13945,Eric Hoffmann,Email,United States,Los Angeles,California,90049,West,Special Projects Muesil,Gluten Free,TEC-AC-10003027,90.57,3,0,11.7741
2,45,CA-2019-118255,2019-03-11 00:00:00,First Class,ON-18715,Odella Nelson,Sales,United States,Eagan,Minnesota,55122,Central,Special Projects Muesil,Gluten Free,TEC-AC-10000171,45.98,2,0,19.7714
3,48,CA-2019-169194,2019-06-20 00:00:00,Standard Class,LH-16900,Lena Hernandez,Email,United States,Dover,Delaware,19901,East,Special Projects Muesil,Gluten Free,TEC-AC-10002167,45,3,0,4.95
4,60,CA-2019-111682,2019-06-17 00:00:00,First Class,TB-21055,Ted Butterfield,Email,United States,Troy,New York,12180,East,Special Projects Muesil,Gluten Free,TEC-AC-10002167,30,2,0,3.3

In [6]:
campaign_raw = pd.read_excel('data/Muesli Project raw data.xlsx', sheet_name='Campaign Data')
campaign_raw.head()

         Order ID Arrival Scan Date     Customer Name
0  CA-2019-109666        2019-05-03      Kunst Miller
1  CA-2019-138933        2019-05-03       Jack Lebron
2  CA-2019-130001        2019-05-03  Heather Kirkland
3  CA-2019-113061        2019-05-06         Ed Ludwig
4  CA-2019-162138        2019-05-06       Grace Kelly

In [7]:
order_process_raw = pd.read_excel('data/Muesli Project raw data.xlsx', sheet_name='Order Process Data')
order_process_raw.head()

   Row ID        Order ID Order Date On Truck Scan Date            Ship Mode
0    3074  CA-2019-125206 2019-01-03         2019-01-07              Express
1    4919  CA-2019-160304 2019-01-02         2019-01-09  Standard Processing
2    4920  CA-2019-160304 2019-01-02         2019-01-09  Standard Processing
3    8604  US-2019-116365 2019-01-03         2019-01-09  Standard Processing
4    8605  US-2019-116365 2019-01-03         2019-01-09  Standard Processing

In [ ]:
order_process_raw = pd.read_excel('data/Muesli Project raw data.xlsx', sheet_name='Order Process Data')
order_process_raw.head()

         Order ID Ready to Ship Date Pickup Date
0  CA-2019-116540         2019-09-02  2019-09-03
1  CA-2019-116540         2019-09-02  2019-09-03
2  CA-2019-129847         2019-09-04  2019-09-04
3  CA-2019-129630         2019-09-04  2019-09-04
4  CA-2019-106278         2019-09-05  2019-09-06

In [51]:
# Understanding df orders_raw
orders_raw.head()
# column names ended up in the first row instead of the proper place

,Index,Order ID,Order Date,Ship Mode,Customer ID,Customer Name,Origin Channel,Country/Region,City,State,Postal Code,Region,Category,Sub-Category,Product ID,Sales,Quantity,Discount,Profit
0,27,CA-2019-121755,2019-01-16,Second Class,EH-13945,Eric Hoffmann,Email,United States,Los Angeles,California,90049.0,West,Special Projects Muesil,Gluten Free,TEC-AC-10003027,90.57,3,0.0,11.7741
1,45,CA-2019-118255,2019-03-11,First Class,ON-18715,Odella Nelson,Sales,United States,Eagan,Minnesota,55122.0,Central,Special Projects Muesil,Gluten Free,TEC-AC-10000171,45.98,2,0.0,19.7714
2,48,CA-2019-169194,2019-06-20,Standard Class,LH-16900,Lena Hernandez,Email,United States,Dover,Delaware,19901.0,East,Special Projects Muesil,Gluten Free,TEC-AC-10002167,45.00,3,0.0,4.9500
3,60,CA-2019-111682,2019-06-17,First Class,TB-21055,Ted Butterfield,Email,United States,Troy,New York,12180.0,East,Special Projects Muesil,Gluten Free,TEC-AC-10002167,30.00,2,0.0,3.3000
4,63,CA-2018-135545,2018-11-24,Standard Class,KM-16720,Kunst Miller,Email,United States,Los Angeles,California,90004.0,West,Special Projects Muesil,Gluten Free,TEC-AC-10004633,13.98,2,0.0,6.1512

In [67]:
orders_clean = orders_raw.copy()                        # making a copy of the database for cleaning purposes
orders_clean.columns = orders_clean.iloc[0]
orders_clean = orders_clean.iloc[1:].reset_index(drop=True)
orders_clean

,Index,Order ID,Order Date,Ship Mode,Customer ID,Customer Name,Origin Channel,Country/Region,City,State,Postal Code,Region,Category,Sub-Category,Product ID,Sales,Quantity,Discount,Profit
0,27,CA-2019-121755,2019-01-16 00:00:00,Second Class,EH-13945,Eric Hoffmann,Email,United States,Los Angeles,California,90049,West,Special Projects Muesil,Gluten Free,TEC-AC-10003027,90.57,3,0,11.7741
1,45,CA-2019-118255,2019-03-11 00:00:00,First Class,ON-18715,Odella Nelson,Sales,United States,Eagan,Minnesota,55122,Central,Special Projects Muesil,Gluten Free,TEC-AC-10000171,45.98,2,0,19.7714
2,48,CA-2019-169194,2019-06-20 00:00:00,Standard Class,LH-16900,Lena Hernandez,Email,United States,Dover,Delaware,19901,East,Special Projects Muesil,Gluten Free,TEC-AC-10002167,45,3,0,4.95
3,60,CA-2019-111682,2019-06-17 00:00:00,First Class,TB-21055,Ted Butterfield,Email,United States,Troy,New York,12180,East,Special Projects Muesil,Gluten Free,TEC-AC-10002167,30,2,0,3.3
4,63,CA-2018-135545,2018-11-24 00:00:00,Standard Class,KM-16720,Kunst Miller,Email,United States,Los Angeles,California,90004,West,Special Projects Muesil,Gluten Free,TEC-AC-10004633,13.98,2,0,6.1512
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,9894,US-2019-115441,2019-07-25 00:00:00,Second Class,SH-19975,Sally Hughsby,Sales,United States,Milwaukee,Wisconsin,53209,Central,Toasted Muesli,With Nuts,FUR-CH-10004626,403.56,4,0,96.8544
9990,9908,US-2018-129007,2018-09-13 00:00:00,First Class,KD-16615,Ken Dana,Sales,United States,Anaheim,California,92804,West,Toasted Muesli,With Nuts,FUR-CH-10000155,717.72,3,0.2,71.772
9991,9913,CA-2018-132388,2018-10-10 00:00:00,First Class,KN-16390,Katherine Nockton,Sales,United States,Santa Barbara,California,93101,West,Toasted Muesli,With Nuts,FUR-CH-10001714,362.136,3,0.2,-54.3204
9992,9920,CA-2019-149272,2019-03-15 00:00:00,Standard Class,MY-18295,Muhammed Yedwab,Sales,United States,Bryan,Texas,77803,Central,Toasted Muesli,With Nuts,FUR-CH-10000863,528.43,5,0.3,-143.431
9993,9948,CA-2020-121559,2020-06-01 00:00:00,Second Class,HW-14935,Helen Wasserman,Sales,United States,Indianapolis,Indiana,46203,Central,Toasted Muesli,With Nuts,FUR-CH-10003746,1925.88,6,0,539.2464

In [68]:
orders_clean.columns.tolist()     # checking column names, we will need to change it to snake_case

['Index',
 'Order ID',
 'Order Date',
 'Ship Mode',
 'Customer ID',
 'Customer Name',
 'Origin Channel',
 'Country/Region',
 'City',
 'State',
 'Postal Code',
 'Region',
 'Category',
 'Sub-Category',
 'Product ID',
 'Sales',
 'Quantity',
 'Discount',
 'Profit']

In [69]:
orders_clean.columns = (orders_clean.columns
                         .str.strip()
                         .str.replace('/', '_', regex=False)                   # turn / into _ first
                         .str.replace('-', '_', regex=False)                   # - → _
                         .str.replace(r'[^a-zA-Z0-9\s_]', '', regex=True)      # then delete anything else unwanted
                         .str.replace(r'\s+', '_', regex=True)
                         .str.lower())
orders_clean.columns.tolist()

['index',
 'order_id',
 'order_date',
 'ship_mode',
 'customer_id',
 'customer_name',
 'origin_channel',
 'country_region',
 'city',
 'state',
 'postal_code',
 'region',
 'category',
 'sub_category',
 'product_id',
 'sales',
 'quantity',
 'discount',
 'profit']

In order to really understand the data, we need to know what information the different columns contain.    
Here are the explanations of the individual variables:


| Column name | Description |
| --- | ----------- |
| index | Unclear, doesn't appear on other tabs |
| order_id | Unique identifier of the order |
| order_date | Day and time of the placement of the order |
| ship_mode | Mode of the shipping: First Class or Second Class |
| customer_id  | Unique identifier of the customer |
| customer_name | First and last nem of the customer |
| origin_channel | How the customer placed the order or found the business? |
| origin_region | Country of the customer |
| city | City of the customer |
| state | State of the customer |
| postal_code | Postal code of the customer |
| region | Region based on internal criteria |
| category | Product Category |
| sub_category | Product sub-category |
| product_id | Unique identifier of the product |
| sales | Total amount paid by the customer (net or gross) |
| quantity | Number of products order |
| discount | Discount |
| profit | Profit, calculation is unclear |

In [70]:
orders_clean.shape

(9994, 19)

In [71]:
orders_clean.info()

<class 'pandas.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 19 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   index           9994 non-null   object
 1   order_id        9994 non-null   str
 2   order_date      9994 non-null   object
 3   ship_mode       9994 non-null   str
 4   customer_id     9994 non-null   str
 5   customer_name   9994 non-null   str
 6   origin_channel  9994 non-null   str
 7   country_region  9994 non-null   str
 8   city            9994 non-null   str
 9   state           9994 non-null   str
 10  postal_code     9983 non-null   object
 11  region          9994 non-null   str
 12  category        9994 non-null   str
 13  sub_category    9994 non-null   str
 14  product_id      9994 non-null   str
 15  sales           9994 non-null   object
 16  quantity        9994 non-null   object
 17  discount        9994 non-null   object
 18  profit          9994 non-null   object
dtypes: object(7), str(12)
memory usage: 1.4+ MB

In [72]:
# index column doesn't serve any purpose, we will rely on order_id, hence it can be dropped
orders_clean = orders_clean.drop(columns='index')

In [73]:
orders_clean.isnull().sum()

0
order_id           0
order_date         0
ship_mode          0
customer_id        0
customer_name      0
origin_channel     0
country_region     0
city               0
state              0
postal_code       11
region             0
category           0
sub_category       0
product_id         0
sales              0
quantity           0
discount           0
profit             0
dtype: int64

In [74]:
# To indentify the missing records
orders_clean[orders_clean['postal_code'].isna()]

,order_id,order_date,ship_mode,customer_id,customer_name,origin_channel,country_region,city,state,postal_code,region,category,sub_category,product_id,sales,quantity,discount,profit
173,CA-2020-104066,2020-12-05 00:00:00,Standard Class,QJ-19255,Quincy Jones,Sales,United States,Burlington,Vermont,NaN,East,Special Projects Muesil,Gluten Free,TEC-AC-10001013,205.03,7,0,67.6599
710,US-2019-165505,2019-01-23 00:00:00,Standard Class,CB-12535,Claudia Bergmann,Sales,United States,Burlington,Vermont,NaN,East,Special Projects Muesil,Gluten Free,TEC-AC-10002926,99.98,2,0,42.9914
1732,US-2020-127292,2020-01-19 00:00:00,Standard Class,RM-19375,Raymond Messe,Email,United States,Burlington,Vermont,NaN,East,Power Muesli,Mega Protein,OFF-AP-10000828,542.94,3,0,152.0232
3408,US-2020-127292,2020-01-19 00:00:00,Standard Class,RM-19375,Raymond Messe,Email,United States,Burlington,Vermont,NaN,East,Power Muesli,Nuts and more,OFF-PA-10000157,79.92,4,0,37.5624
3409,US-2020-127292,2020-01-19 00:00:00,Standard Class,RM-19375,Raymond Messe,Email,United States,Burlington,Vermont,NaN,East,Power Muesli,Nuts and more,OFF-PA-10001970,12.28,1,0,5.7716
4279,US-2019-150140,2019-04-06 00:00:00,Standard Class,VM-21685,Valerie Mitchum,Facebook,United States,Burlington,Vermont,NaN,East,Special Projects Muesil,Only Oats,TEC-PH-10002555,1294.75,5,0,336.635
4694,US-2020-127292,2020-01-19 00:00:00,Standard Class,RM-19375,Raymond Messe,Email,United States,Burlington,Vermont,NaN,East,Power Muesli,Power Clean Fibre Boost,OFF-EN-10001509,2.04,1,0,0.9588
5490,US-2019-165505,2019-01-23 00:00:00,Standard Class,CB-12535,Claudia Bergmann,Sales,United States,Burlington,Vermont,NaN,East,Power Muesli,Steel Cut,OFF-ST-10001526,1564.29,13,0,406.7154
7802,US-2019-165505,2019-01-23 00:00:00,Standard Class,CB-12535,Claudia Bergmann,Sales,United States,Burlington,Vermont,NaN,East,Power Muesli,Super Mega Protein,OFF-AR-10003477,8.04,6,0,2.7336
8415,CA-2018-117086,2018-11-08 00:00:00,Standard Class,QJ-19255,Quincy Jones,Sales,United States,Burlington,Vermont,NaN,East,Toasted Muesli,With Fruit,FUR-BO-10004834,4404.9,5,0,1013.127
9693,CA-2018-162887,2018-11-07 00:00:00,Second Class,SV-20785,Stewart Visinsky,Email,United States,Burlington,Vermont,NaN,East,Toasted Muesli,With Nuts,FUR-CH-10000595,715.2,3,0,178.8

In [75]:
#To check the postal codes that do exist for Burlington, Vermont in the dataset
orders_clean[
    (orders_clean['city'] == 'Burlington') &
    (orders_clean['state'] == 'Vermont')
]['postal_code'].value_counts(dropna=False)

postal_code
NaN    11
Name: count, dtype: int64

In [76]:
# we check all orders from Burlington and Vermont
orders_clean[
    (orders_clean['city'] == 'Burlington') &
    (orders_clean['state'] == 'Vermont')
][['customer_id', 'postal_code']]
#  we have 5 customers from Burlington, Vermont, their postal_code is all missing, 
# but since we won't analyze postal_code data, we can impute a real value from this city

0    customer_id postal_code
173     QJ-19255         NaN
710     CB-12535         NaN
1732    RM-19375         NaN
3408    RM-19375         NaN
3409    RM-19375         NaN
4279    VM-21685         NaN
4694    RM-19375         NaN
5490    CB-12535         NaN
7802    CB-12535         NaN
8415    QJ-19255         NaN
9693    SV-20785         NaN

In [77]:
#To fill in the postal code 
orders_clean.loc[
    orders_clean['postal_code'].isna(),
    'postal_code'
] = '05401'

In [ ]:
orders_clean.isnull().sum()

0
order_id          0
order_date        0
ship_mode         0
customer_id       0
customer_name     0
origin_channel    0
country_region    0
city              0
state             0
postal_code       0
region            0
category          0
sub_category      0
product_id        0
sales             0
quantity          0
discount          0
profit            0
dtype: int64

In [79]:
orders_clean.duplicated().sum()

np.int64(1)

In [80]:
orders_clean[orders_clean.duplicated(keep=False)]
# one duplicated row, needs to be dropped

,order_id,order_date,ship_mode,customer_id,customer_name,origin_channel,country_region,city,state,postal_code,region,category,sub_category,product_id,sales,quantity,discount,profit
9579,US-2017-150119,2017-04-23 00:00:00,Standard Class,LB-16795,Laurel Beltran,Facebook,United States,Columbus,Ohio,43229,East,Toasted Muesli,With Nuts,FUR-CH-10002965,281.372,2,0.3,-12.0588
9580,US-2017-150119,2017-04-23 00:00:00,Standard Class,LB-16795,Laurel Beltran,Facebook,United States,Columbus,Ohio,43229,East,Toasted Muesli,With Nuts,FUR-CH-10002965,281.372,2,0.3,-12.0588

In [81]:
orders_clean = orders_clean.drop_duplicates()
print(orders_clean.duplicated().sum())

0

In [82]:
#To fix the data types

orders_clean['order_date'] = pd.to_datetime(orders_clean['order_date'])

orders_clean['sales'] = pd.to_numeric(orders_clean['sales'])
orders_clean['quantity'] = pd.to_numeric(orders_clean['quantity'])
orders_clean['discount'] = pd.to_numeric(orders_clean['discount'])
orders_clean['profit'] = pd.to_numeric(orders_clean['profit'])

In [83]:
orders_clean.dtypes

0
order_id                     str
order_date        datetime64[us]
ship_mode                    str
customer_id                  str
customer_name                str
origin_channel               str
country_region               str
city                         str
state                        str
postal_code               object
region                       str
category                     str
sub_category                 str
product_id                   str
sales                    float64
quantity                   int64
discount                 float64
profit                   float64
dtype: object

In [85]:
orders_clean['ship_mode'].value_counts()

ship_mode
Standard Class    5967
First Class       2081
Second Class      1945
Name: count, dtype: int64

In [86]:
orders_clean['origin_channel'].value_counts()

origin_channel
Email       5191
Sales       3020
Facebook    1782
Name: count, dtype: int64

In [87]:
orders_clean['region'].value_counts()

region
West       3203
East       2847
Central    2323
South      1620
Name: count, dtype: int64

In [88]:
orders_clean['category'].value_counts()

category
Power Muesli               6026
Toasted Muesli             2120
Special Projects Muesil    1847
Name: count, dtype: int64

In [90]:
orders_clean[['sales', 'quantity', 'discount', 'profit']].describe()

0             sales     quantity     discount       profit
count   9993.000000  9993.000000  9993.000000  9993.000000
mean     229.852846     3.789753     0.156188    28.660971
std      623.276074     2.225149     0.206457   234.271476
min        0.444000     1.000000     0.000000 -6599.978000
25%       17.280000     2.000000     0.000000     1.731000
50%       54.480000     3.000000     0.200000     8.671000
75%      209.940000     5.000000     0.200000    29.364000
max    22638.480000    14.000000     0.800000  8399.976000

In [91]:
orders_clean['order_id'].nunique()

5009

In [93]:
orders_clean['customer_id'].nunique()

793

In [ ]:
orders_clean['product_id'].nunique()

1862

In [96]:
Q1 = orders_clean['sales'].quantile(0.25)
Q3 = orders_clean['sales'].quantile(0.75)

IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

print("Sales lower bound:", lower)
print("Sales upper bound:", upper)

Sales lower bound: -271.71000000000004
Sales upper bound: 498.93

In [99]:
orders_clean[orders_clean['sales'] < 0]

Empty DataFrame
Columns: [order_id, order_date, ship_mode, customer_id, customer_name, origin_channel, country_region, city, state, postal_code, region, category, sub_category, product_id, sales, quantity, discount, profit]
Index: []

In [100]:
orders_clean[orders_clean['quantity'] <= 0]

Empty DataFrame
Columns: [order_id, order_date, ship_mode, customer_id, customer_name, origin_channel, country_region, city, state, postal_code, region, category, sub_category, product_id, sales, quantity, discount, profit]
Index: []

In [101]:
orders_clean[orders_clean['discount'] < 0]

Empty DataFrame
Columns: [order_id, order_date, ship_mode, customer_id, customer_name, origin_channel, country_region, city, state, postal_code, region, category, sub_category, product_id, sales, quantity, discount, profit]
Index: []

In [102]:
orders_clean[orders_clean['discount'] > 1]

Empty DataFrame
Columns: [order_id, order_date, ship_mode, customer_id, customer_name, origin_channel, country_region, city, state, postal_code, region, category, sub_category, product_id, sales, quantity, discount, profit]
Index: []