In [1]:
import pandas as pd

In [5]:
# reading the data
orders_raw = pd.read_excel('data/Muesli Project raw data.xlsx', sheet_name='Orders')
orders_raw.head()

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18
0,Index,Order ID,Order Date,Ship Mode,Customer ID,Customer Name,Origin Channel,Country/Region,City,State,Postal Code,Region,Category,Sub-Category,Product ID,Sales,Quantity,Discount,Profit
1,27,CA-2019-121755,2019-01-16 00:00:00,Second Class,EH-13945,Eric Hoffmann,Email,United States,Los Angeles,California,90049,West,Special Projects Muesil,Gluten Free,TEC-AC-10003027,90.57,3,0,11.7741
2,45,CA-2019-118255,2019-03-11 00:00:00,First Class,ON-18715,Odella Nelson,Sales,United States,Eagan,Minnesota,55122,Central,Special Projects Muesil,Gluten Free,TEC-AC-10000171,45.98,2,0,19.7714
3,48,CA-2019-169194,2019-06-20 00:00:00,Standard Class,LH-16900,Lena Hernandez,Email,United States,Dover,Delaware,19901,East,Special Projects Muesil,Gluten Free,TEC-AC-10002167,45,3,0,4.95
4,60,CA-2019-111682,2019-06-17 00:00:00,First Class,TB-21055,Ted Butterfield,Email,United States,Troy,New York,12180,East,Special Projects Muesil,Gluten Free,TEC-AC-10002167,30,2,0,3.3

In [6]:
campaign_raw = pd.read_excel('data/Muesli Project raw data.xlsx', sheet_name='Campaign Data')
campaign_raw.head()

         Order ID Arrival Scan Date     Customer Name
0  CA-2019-109666        2019-05-03      Kunst Miller
1  CA-2019-138933        2019-05-03       Jack Lebron
2  CA-2019-130001        2019-05-03  Heather Kirkland
3  CA-2019-113061        2019-05-06         Ed Ludwig
4  CA-2019-162138        2019-05-06       Grace Kelly

In [7]:
order_process_raw = pd.read_excel('data/Muesli Project raw data.xlsx', sheet_name='Order Process Data')
order_process_raw.head()

   Row ID        Order ID Order Date On Truck Scan Date            Ship Mode
0    3074  CA-2019-125206 2019-01-03         2019-01-07              Express
1    4919  CA-2019-160304 2019-01-02         2019-01-09  Standard Processing
2    4920  CA-2019-160304 2019-01-02         2019-01-09  Standard Processing
3    8604  US-2019-116365 2019-01-03         2019-01-09  Standard Processing
4    8605  US-2019-116365 2019-01-03         2019-01-09  Standard Processing

In [8]:
intern_data_raw = pd.read_excel('data/Muesli Project raw data.xlsx', sheet_name='InternData Study')
intern_data_raw.head()

         Order ID Ready to Ship Date Pickup Date
0  CA-2019-116540         2019-09-02  2019-09-03
1  CA-2019-116540         2019-09-02  2019-09-03
2  CA-2019-129847         2019-09-04  2019-09-04
3  CA-2019-129630         2019-09-04  2019-09-04
4  CA-2019-106278         2019-09-05  2019-09-06

In [ ]:
# Understanding df orders_raw
orders_raw.head()
# column names ended up in the first row instead of the proper place

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18
0,Index,Order ID,Order Date,Ship Mode,Customer ID,Customer Name,Origin Channel,Country/Region,City,State,Postal Code,Region,Category,Sub-Category,Product ID,Sales,Quantity,Discount,Profit
1,27,CA-2019-121755,2019-01-16 00:00:00,Second Class,EH-13945,Eric Hoffmann,Email,United States,Los Angeles,California,90049,West,Special Projects Muesil,Gluten Free,TEC-AC-10003027,90.57,3,0,11.7741
2,45,CA-2019-118255,2019-03-11 00:00:00,First Class,ON-18715,Odella Nelson,Sales,United States,Eagan,Minnesota,55122,Central,Special Projects Muesil,Gluten Free,TEC-AC-10000171,45.98,2,0,19.7714
3,48,CA-2019-169194,2019-06-20 00:00:00,Standard Class,LH-16900,Lena Hernandez,Email,United States,Dover,Delaware,19901,East,Special Projects Muesil,Gluten Free,TEC-AC-10002167,45,3,0,4.95
4,60,CA-2019-111682,2019-06-17 00:00:00,First Class,TB-21055,Ted Butterfield,Email,United States,Troy,New York,12180,East,Special Projects Muesil,Gluten Free,TEC-AC-10002167,30,2,0,3.3

In [18]:
orders_clean = orders_raw.copy()                        # making a copy of the database for cleaning purposes
orders_clean.columns = orders_clean.iloc[0]             # take row 0's values, use them as the new column names
orders_clean = orders_clean[1:].reset_index(drop=True)  # drop row 0 from the data, then fix the index gap
orders_clean.head()

,Index,Order ID,Order Date,Ship Mode,Customer ID,Customer Name,Origin Channel,Country/Region,City,State,Postal Code,Region,Category,Sub-Category,Product ID,Sales,Quantity,Discount,Profit
0,27,CA-2019-121755,2019-01-16 00:00:00,Second Class,EH-13945,Eric Hoffmann,Email,United States,Los Angeles,California,90049,West,Special Projects Muesil,Gluten Free,TEC-AC-10003027,90.57,3,0,11.7741
1,45,CA-2019-118255,2019-03-11 00:00:00,First Class,ON-18715,Odella Nelson,Sales,United States,Eagan,Minnesota,55122,Central,Special Projects Muesil,Gluten Free,TEC-AC-10000171,45.98,2,0,19.7714
2,48,CA-2019-169194,2019-06-20 00:00:00,Standard Class,LH-16900,Lena Hernandez,Email,United States,Dover,Delaware,19901,East,Special Projects Muesil,Gluten Free,TEC-AC-10002167,45,3,0,4.95
3,60,CA-2019-111682,2019-06-17 00:00:00,First Class,TB-21055,Ted Butterfield,Email,United States,Troy,New York,12180,East,Special Projects Muesil,Gluten Free,TEC-AC-10002167,30,2,0,3.3
4,63,CA-2018-135545,2018-11-24 00:00:00,Standard Class,KM-16720,Kunst Miller,Email,United States,Los Angeles,California,90004,West,Special Projects Muesil,Gluten Free,TEC-AC-10004633,13.98,2,0,6.1512

In [19]:
orders_clean.columns.tolist()     # checking column names, we will need to change it to snake_case

['Index',
 'Order ID',
 'Order Date',
 'Ship Mode',
 'Customer ID',
 'Customer Name',
 'Origin Channel',
 'Country/Region',
 'City',
 'State',
 'Postal Code',
 'Region',
 'Category',
 'Sub-Category',
 'Product ID',
 'Sales',
 'Quantity',
 'Discount',
 'Profit']

In [20]:
orders_clean.columns = (orders_clean.columns
                         .str.strip()
                         .str.replace('/', '_', regex=False)                   # turn / into _ first
                         .str.replace('-', '_', regex=False)                   # - → _
                         .str.replace(r'[^a-zA-Z0-9\s_]', '', regex=True)      # then delete anything else unwanted
                         .str.replace(r'\s+', '_', regex=True)
                         .str.lower())
orders_clean.columns.tolist()

['index',
 'order_id',
 'order_date',
 'ship_mode',
 'customer_id',
 'customer_name',
 'origin_channel',
 'country_region',
 'city',
 'state',
 'postal_code',
 'region',
 'category',
 'sub_category',
 'product_id',
 'sales',
 'quantity',
 'discount',
 'profit']

In order to really understand the data, we need to know what information the different columns contain.    
Here are the explanations of the individual variables:


| Column name | Description |
| --- | ----------- |
| index | |
| order_id | |
| order_date | |
| ship_mode |  |
| customer_id  |  |
| customer_name |  |
| origin_channel | |
| origin_region | |
| city |  |
| state |  |
| postal_code |  |
| region |  |
| category |  |
| sub_category |  |
| product_id |  |
| sales |  |
| quantity |  |
| discount |  |
| profit |  |