In [15]:
import pandas as pd

In [16]:
%pip install openpyxl

Requirement already satisfied: openpyxl in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from openpyxl) (2.0.0)
Note: you may need to restart the kernel to use updated packages.

In [65]:
order_process_raw = pd.read_excel("/Users/mangchinpar/Desktop/DA File/Muesli-Project-Group3-/data/Muesli Project raw data.xlsx")
order_process_raw.head()

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18
0,Index,Order ID,Order Date,Ship Mode,Customer ID,Customer Name,Origin Channel,Country/Region,City,State,Postal Code,Region,Category,Sub-Category,Product ID,Sales,Quantity,Discount,Profit
1,27,CA-2019-121755,2019-01-16 00:00:00,Second Class,EH-13945,Eric Hoffmann,Email,United States,Los Angeles,California,90049,West,Special Projects Muesil,Gluten Free,TEC-AC-10003027,90.57,3,0,11.7741
2,45,CA-2019-118255,2019-03-11 00:00:00,First Class,ON-18715,Odella Nelson,Sales,United States,Eagan,Minnesota,55122,Central,Special Projects Muesil,Gluten Free,TEC-AC-10000171,45.98,2,0,19.7714
3,48,CA-2019-169194,2019-06-20 00:00:00,Standard Class,LH-16900,Lena Hernandez,Email,United States,Dover,Delaware,19901,East,Special Projects Muesil,Gluten Free,TEC-AC-10002167,45,3,0,4.95
4,60,CA-2019-111682,2019-06-17 00:00:00,First Class,TB-21055,Ted Butterfield,Email,United States,Troy,New York,12180,East,Special Projects Muesil,Gluten Free,TEC-AC-10002167,30,2,0,3.3

In [22]:
order_process_raw.columns = order_process_raw.iloc[0]
order_process_raw = order_process_raw.iloc[1:].reset_index(drop=True)
order_process_raw

,Index,Order ID,Order Date,Ship Mode,Customer ID,Customer Name,Origin Channel,Country/Region,City,State,Postal Code,Region,Category,Sub-Category,Product ID,Sales,Quantity,Discount,Profit
0,27,CA-2019-121755,2019-01-16 00:00:00,Second Class,EH-13945,Eric Hoffmann,Email,United States,Los Angeles,California,90049,West,Special Projects Muesil,Gluten Free,TEC-AC-10003027,90.57,3,0,11.7741
1,45,CA-2019-118255,2019-03-11 00:00:00,First Class,ON-18715,Odella Nelson,Sales,United States,Eagan,Minnesota,55122,Central,Special Projects Muesil,Gluten Free,TEC-AC-10000171,45.98,2,0,19.7714
2,48,CA-2019-169194,2019-06-20 00:00:00,Standard Class,LH-16900,Lena Hernandez,Email,United States,Dover,Delaware,19901,East,Special Projects Muesil,Gluten Free,TEC-AC-10002167,45,3,0,4.95
3,60,CA-2019-111682,2019-06-17 00:00:00,First Class,TB-21055,Ted Butterfield,Email,United States,Troy,New York,12180,East,Special Projects Muesil,Gluten Free,TEC-AC-10002167,30,2,0,3.3
4,63,CA-2018-135545,2018-11-24 00:00:00,Standard Class,KM-16720,Kunst Miller,Email,United States,Los Angeles,California,90004,West,Special Projects Muesil,Gluten Free,TEC-AC-10004633,13.98,2,0,6.1512
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,9894,US-2019-115441,2019-07-25 00:00:00,Second Class,SH-19975,Sally Hughsby,Sales,United States,Milwaukee,Wisconsin,53209,Central,Toasted Muesli,With Nuts,FUR-CH-10004626,403.56,4,0,96.8544
9990,9908,US-2018-129007,2018-09-13 00:00:00,First Class,KD-16615,Ken Dana,Sales,United States,Anaheim,California,92804,West,Toasted Muesli,With Nuts,FUR-CH-10000155,717.72,3,0.2,71.772
9991,9913,CA-2018-132388,2018-10-10 00:00:00,First Class,KN-16390,Katherine Nockton,Sales,United States,Santa Barbara,California,93101,West,Toasted Muesli,With Nuts,FUR-CH-10001714,362.136,3,0.2,-54.3204
9992,9920,CA-2019-149272,2019-03-15 00:00:00,Standard Class,MY-18295,Muhammed Yedwab,Sales,United States,Bryan,Texas,77803,Central,Toasted Muesli,With Nuts,FUR-CH-10000863,528.43,5,0.3,-143.431
9993,9948,CA-2020-121559,2020-06-01 00:00:00,Second Class,HW-14935,Helen Wasserman,Sales,United States,Indianapolis,Indiana,46203,Central,Toasted Muesli,With Nuts,FUR-CH-10003746,1925.88,6,0,539.2464

In [23]:
order_process_raw.head()

,Index,Order ID,Order Date,Ship Mode,Customer ID,Customer Name,Origin Channel,Country/Region,City,State,Postal Code,Region,Category,Sub-Category,Product ID,Sales,Quantity,Discount,Profit
0,27,CA-2019-121755,2019-01-16 00:00:00,Second Class,EH-13945,Eric Hoffmann,Email,United States,Los Angeles,California,90049,West,Special Projects Muesil,Gluten Free,TEC-AC-10003027,90.57,3,0,11.7741
1,45,CA-2019-118255,2019-03-11 00:00:00,First Class,ON-18715,Odella Nelson,Sales,United States,Eagan,Minnesota,55122,Central,Special Projects Muesil,Gluten Free,TEC-AC-10000171,45.98,2,0,19.7714
2,48,CA-2019-169194,2019-06-20 00:00:00,Standard Class,LH-16900,Lena Hernandez,Email,United States,Dover,Delaware,19901,East,Special Projects Muesil,Gluten Free,TEC-AC-10002167,45,3,0,4.95
3,60,CA-2019-111682,2019-06-17 00:00:00,First Class,TB-21055,Ted Butterfield,Email,United States,Troy,New York,12180,East,Special Projects Muesil,Gluten Free,TEC-AC-10002167,30,2,0,3.3
4,63,CA-2018-135545,2018-11-24 00:00:00,Standard Class,KM-16720,Kunst Miller,Email,United States,Los Angeles,California,90004,West,Special Projects Muesil,Gluten Free,TEC-AC-10004633,13.98,2,0,6.1512

In [24]:
order_process_raw.shape

(9994, 19)

In [25]:
order_process_raw.info()

<class 'pandas.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 19 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Index           9994 non-null   object
 1   Order ID        9994 non-null   str
 2   Order Date      9994 non-null   object
 3   Ship Mode       9994 non-null   str
 4   Customer ID     9994 non-null   str
 5   Customer Name   9994 non-null   str
 6   Origin Channel  9994 non-null   str
 7   Country/Region  9994 non-null   str
 8   City            9994 non-null   str
 9   State           9994 non-null   str
 10  Postal Code     9983 non-null   object
 11  Region          9994 non-null   str
 12  Category        9994 non-null   str
 13  Sub-Category    9994 non-null   str
 14  Product ID      9994 non-null   str
 15  Sales           9994 non-null   object
 16  Quantity        9994 non-null   object
 17  Discount        9994 non-null   object
 18  Profit          9994 non-null   object
dtypes: object(7), str(12)
memory usage: 1.4+ MB

In [26]:
order_process_raw.isnull().sum()

0
Index              0
Order ID           0
Order Date         0
Ship Mode          0
Customer ID        0
Customer Name      0
Origin Channel     0
Country/Region     0
City               0
State              0
Postal Code       11
Region             0
Category           0
Sub-Category       0
Product ID         0
Sales              0
Quantity           0
Discount           0
Profit             0
dtype: int64

In [28]:
#To indentify the missing records
order_process_raw[order_process_raw['Postal Code'].isna()]

,Index,Order ID,Order Date,Ship Mode,Customer ID,Customer Name,Origin Channel,Country/Region,City,State,Postal Code,Region,Category,Sub-Category,Product ID,Sales,Quantity,Discount,Profit
173,2235,CA-2020-104066,2020-12-05 00:00:00,Standard Class,QJ-19255,Quincy Jones,Sales,United States,Burlington,Vermont,NaN,East,Special Projects Muesil,Gluten Free,TEC-AC-10001013,205.03,7,0,67.6599
710,9147,US-2019-165505,2019-01-23 00:00:00,Standard Class,CB-12535,Claudia Bergmann,Sales,United States,Burlington,Vermont,NaN,East,Special Projects Muesil,Gluten Free,TEC-AC-10002926,99.98,2,0,42.9914
1732,9389,US-2020-127292,2020-01-19 00:00:00,Standard Class,RM-19375,Raymond Messe,Email,United States,Burlington,Vermont,NaN,East,Power Muesli,Mega Protein,OFF-AP-10000828,542.94,3,0,152.0232
3408,9387,US-2020-127292,2020-01-19 00:00:00,Standard Class,RM-19375,Raymond Messe,Email,United States,Burlington,Vermont,NaN,East,Power Muesli,Nuts and more,OFF-PA-10000157,79.92,4,0,37.5624
3409,9388,US-2020-127292,2020-01-19 00:00:00,Standard Class,RM-19375,Raymond Messe,Email,United States,Burlington,Vermont,NaN,East,Power Muesli,Nuts and more,OFF-PA-10001970,12.28,1,0,5.7716
4279,8799,US-2019-150140,2019-04-06 00:00:00,Standard Class,VM-21685,Valerie Mitchum,Facebook,United States,Burlington,Vermont,NaN,East,Special Projects Muesil,Only Oats,TEC-PH-10002555,1294.75,5,0,336.635
4694,9390,US-2020-127292,2020-01-19 00:00:00,Standard Class,RM-19375,Raymond Messe,Email,United States,Burlington,Vermont,NaN,East,Power Muesli,Power Clean Fibre Boost,OFF-EN-10001509,2.04,1,0,0.9588
5490,9149,US-2019-165505,2019-01-23 00:00:00,Standard Class,CB-12535,Claudia Bergmann,Sales,United States,Burlington,Vermont,NaN,East,Power Muesli,Steel Cut,OFF-ST-10001526,1564.29,13,0,406.7154
7802,9148,US-2019-165505,2019-01-23 00:00:00,Standard Class,CB-12535,Claudia Bergmann,Sales,United States,Burlington,Vermont,NaN,East,Power Muesli,Super Mega Protein,OFF-AR-10003477,8.04,6,0,2.7336
8415,9742,CA-2018-117086,2018-11-08 00:00:00,Standard Class,QJ-19255,Quincy Jones,Sales,United States,Burlington,Vermont,NaN,East,Toasted Muesli,With Fruit,FUR-BO-10004834,4404.9,5,0,1013.127
9693,5275,CA-2018-162887,2018-11-07 00:00:00,Second Class,SV-20785,Stewart Visinsky,Email,United States,Burlington,Vermont,NaN,East,Toasted Muesli,With Nuts,FUR-CH-10000595,715.2,3,0,178.8

In [29]:
#To check the postal codes that do exist for Burlington, Vermont in the dataset
order_process_raw[
    (order_process_raw['City'] == 'Burlington') &
    (order_process_raw['State'] == 'Vermont')
]['Postal Code'].value_counts(dropna=False)

Postal Code
NaN    11
Name: count, dtype: int64

**There are no non-missing Postal Codes for Burlington, Vermont anywhere in the dataset.**

In [30]:
#To fill in the postal code with the one that I find in google.
order_process_raw.loc[
    order_process_raw['Postal Code'].isna(),
    'Postal Code'
] = '05401'

In [31]:
order_process_raw.isnull().sum()

0
Index             0
Order ID          0
Order Date        0
Ship Mode         0
Customer ID       0
Customer Name     0
Origin Channel    0
Country/Region    0
City              0
State             0
Postal Code       0
Region            0
Category          0
Sub-Category      0
Product ID        0
Sales             0
Quantity          0
Discount          0
Profit            0
dtype: int64

In [27]:
order_process_raw.duplicated().sum()

np.int64(0)

In [32]:
#To fix the data types

order_process_raw['Order Date'] = pd.to_datetime(order_process_raw['Order Date'])

order_process_raw['Sales'] = pd.to_numeric(order_process_raw['Sales'])
order_process_raw['Quantity'] = pd.to_numeric(order_process_raw['Quantity'])
order_process_raw['Discount'] = pd.to_numeric(order_process_raw['Discount'])
order_process_raw['Profit'] = pd.to_numeric(order_process_raw['Profit'])

In [33]:
order_process_raw.dtypes

0
Index                     object
Order ID                     str
Order Date        datetime64[us]
Ship Mode                    str
Customer ID                  str
Customer Name                str
Origin Channel               str
Country/Region               str
City                         str
State                        str
Postal Code               object
Region                       str
Category                     str
Sub-Category                 str
Product ID                   str
Sales                    float64
Quantity                   int64
Discount                 float64
Profit                   float64
dtype: object

**To Check the categorical values**

In [34]:
order_process_raw['Ship Mode'].value_counts()

Ship Mode
Standard Class    5968
First Class       2081
Second Class      1945
Name: count, dtype: int64

In [35]:
order_process_raw['Origin Channel'].value_counts()

Origin Channel
Email       5191
Sales       3020
Facebook    1783
Name: count, dtype: int64

In [36]:
order_process_raw['Region'].value_counts()

Region
West       3203
East       2848
Central    2323
South      1620
Name: count, dtype: int64

In [37]:
order_process_raw['Category'].value_counts()

Category
Power Muesli               6026
Toasted Muesli             2121
Special Projects Muesil    1847
Name: count, dtype: int64

**To check numeric column**

In [38]:
order_process_raw[['Sales', 'Quantity', 'Discount', 'Profit']].describe()

0             Sales     Quantity     Discount       Profit
count   9994.000000  9994.000000  9994.000000  9994.000000
mean     229.858001     3.789574     0.156203    28.656896
std      623.245101     2.225110     0.206452   234.260108
min        0.444000     1.000000     0.000000 -6599.978000
25%       17.280000     2.000000     0.000000     1.728750
50%       54.490000     3.000000     0.200000     8.666500
75%      209.940000     5.000000     0.200000    29.364000
max    22638.480000    14.000000     0.800000  8399.976000

**To check the key column to understand the grain of the dataset.**

In [40]:
order_process_raw['Order ID'].nunique()

5009

In [41]:
order_process_raw['Customer ID'].nunique()

793

In [42]:
order_process_raw['Product ID'].nunique()

1862

**Renaming the columns**

In [44]:
order_process_raw.columns = (
    order_process_raw.columns
    .str.strip()
    .str.lower()
    .str.replace(' ', '_')
    .str.replace('/', '_')
    .str.replace('-', '_')
)

order_process_raw.head()

,index,order_id,order_date,ship_mode,customer_id,customer_name,origin_channel,country_region,city,state,postal_code,region,category,sub_category,product_id,sales,quantity,discount,profit
0,27,CA-2019-121755,2019-01-16,Second Class,EH-13945,Eric Hoffmann,Email,United States,Los Angeles,California,90049,West,Special Projects Muesil,Gluten Free,TEC-AC-10003027,90.57,3,0.0,11.7741
1,45,CA-2019-118255,2019-03-11,First Class,ON-18715,Odella Nelson,Sales,United States,Eagan,Minnesota,55122,Central,Special Projects Muesil,Gluten Free,TEC-AC-10000171,45.98,2,0.0,19.7714
2,48,CA-2019-169194,2019-06-20,Standard Class,LH-16900,Lena Hernandez,Email,United States,Dover,Delaware,19901,East,Special Projects Muesil,Gluten Free,TEC-AC-10002167,45.00,3,0.0,4.9500
3,60,CA-2019-111682,2019-06-17,First Class,TB-21055,Ted Butterfield,Email,United States,Troy,New York,12180,East,Special Projects Muesil,Gluten Free,TEC-AC-10002167,30.00,2,0.0,3.3000
4,63,CA-2018-135545,2018-11-24,Standard Class,KM-16720,Kunst Miller,Email,United States,Los Angeles,California,90004,West,Special Projects Muesil,Gluten Free,TEC-AC-10004633,13.98,2,0.0,6.1512

**Checking numerical range and outlier**

In [46]:
order_process_raw[['sales', 'quantity', 'discount', 'profit']].describe()

0             sales     quantity     discount       profit
count   9994.000000  9994.000000  9994.000000  9994.000000
mean     229.858001     3.789574     0.156203    28.656896
std      623.245101     2.225110     0.206452   234.260108
min        0.444000     1.000000     0.000000 -6599.978000
25%       17.280000     2.000000     0.000000     1.728750
50%       54.490000     3.000000     0.200000     8.666500
75%      209.940000     5.000000     0.200000    29.364000
max    22638.480000    14.000000     0.800000  8399.976000

In [59]:
Q1 = order_process_raw['sales'].quantile(0.25)
Q3 = order_process_raw['sales'].quantile(0.75)

IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

print("Sales lower bound:", lower)
print("Sales upper bound:", upper)

Sales lower bound: -271.71000000000004
Sales upper bound: 498.93

**To check suspicious value**

In [48]:
order_process_raw[order_process_raw['sales'] < 0]

Empty DataFrame
Columns: [index, order_id, order_date, ship_mode, customer_id, customer_name, origin_channel, country_region, city, state, postal_code, region, category, sub_category, product_id, sales, quantity, discount, profit]
Index: []

In [49]:
order_process_raw[order_process_raw['quantity'] <= 0]

Empty DataFrame
Columns: [index, order_id, order_date, ship_mode, customer_id, customer_name, origin_channel, country_region, city, state, postal_code, region, category, sub_category, product_id, sales, quantity, discount, profit]
Index: []

In [50]:
order_process_raw[order_process_raw['discount'] < 0]

Empty DataFrame
Columns: [index, order_id, order_date, ship_mode, customer_id, customer_name, origin_channel, country_region, city, state, postal_code, region, category, sub_category, product_id, sales, quantity, discount, profit]
Index: []

In [51]:
order_process_raw[order_process_raw['discount'] > 1]

Empty DataFrame
Columns: [index, order_id, order_date, ship_mode, customer_id, customer_name, origin_channel, country_region, city, state, postal_code, region, category, sub_category, product_id, sales, quantity, discount, profit]
Index: []

In [52]:
order_process_raw[order_process_raw['profit'] < 0]

,index,order_id,order_date,ship_mode,customer_id,customer_name,origin_channel,country_region,city,state,postal_code,region,category,sub_category,product_id,sales,quantity,discount,profit
6,101,CA-2019-158568,2019-08-29,Standard Class,RB-19465,Rick Bensley,Facebook,United States,Chicago,Illinois,60610,Central,Special Projects Muesil,Gluten Free,TEC-AC-10001767,95.976,3,0.2,-10.7973
7,104,US-2018-156867,2018-11-13,Standard Class,LC-16870,Lena Cacioppo,Email,United States,Aurora,Colorado,80013,West,Special Projects Muesil,Gluten Free,TEC-AC-10001552,238.896,6,0.2,-26.8758
16,236,US-2020-100930,2020-04-07,Standard Class,CS-12400,Christopher Schild,Facebook,United States,Tampa,Florida,33614,South,Special Projects Muesil,Gluten Free,TEC-AC-10003832,617.976,3,0.2,-7.7247
27,376,US-2017-119137,2017-07-23,Standard Class,AG-10900,Arthur Gainer,Email,United States,Tucson,Arizona,85705,West,Special Projects Muesil,Gluten Free,TEC-AC-10002076,479.040,10,0.2,-29.9400
29,386,US-2018-168935,2018-11-27,Standard Class,DO-13435,Denny Ordway,Email,United States,Pembroke Pines,Florida,33024,South,Special Projects Muesil,Gluten Free,TEC-AC-10002335,83.976,3,0.2,-1.0497
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9982,9791,CA-2020-144491,2020-03-27,Standard Class,CJ-12010,Caroline Jumper,Email,United States,Houston,Texas,77070,Central,Toasted Muesli,With Nuts,FUR-CH-10001714,211.246,2,0.3,-66.3916
9983,9793,CA-2017-127166,2017-05-21,Second Class,KH-16360,Katherine Hughes,Email,United States,Houston,Texas,77070,Central,Toasted Muesli,With Nuts,FUR-CH-10003396,107.772,2,0.3,-29.2524
9985,9827,US-2017-164406,2017-08-15,Standard Class,BD-11605,Brian Dahlen,Email,United States,San Francisco,California,94122,West,Toasted Muesli,With Nuts,FUR-CH-10003833,195.136,4,0.2,-12.1960
9991,9913,CA-2018-132388,2018-10-10,First Class,KN-16390,Katherine Nockton,Sales,United States,Santa Barbara,California,93101,West,Toasted Muesli,With Nuts,FUR-CH-10001714,362.136,3,0.2,-54.3204
9992,9920,CA-2019-149272,2019-03-15,Standard Class,MY-18295,Muhammed Yedwab,Sales,United States,Bryan,Texas,77803,Central,Toasted Muesli,With Nuts,FUR-CH-10000863,528.430,5,0.3,-143.4310

**To check whether your identifiers behave as expected**

In [54]:
order_process_raw['order_id'].nunique()

5009

In [55]:
order_process_raw['customer_id'].nunique()

793

In [56]:
order_process_raw['product_id'].nunique()

1862

In [57]:
#to check repeated orders

order_process_raw['order_id'].value_counts().head(10)

order_id
CA-2020-100111    14
CA-2020-157987    12
CA-2019-165330    11
US-2019-108504    11
CA-2018-131338    10
US-2018-126977    10
CA-2019-105732    10
CA-2020-117457     9
CA-2017-106439     9
CA-2020-140949     9
Name: count, dtype: int64

In [58]:
#To check whether the customer has multiple orders

order_process_raw.groupby('customer_id')['order_id'].nunique().describe()

count    793.000000
mean       6.316520
std        2.550885
min        1.000000
25%        5.000000
50%        6.000000
75%        8.000000
max       17.000000
Name: order_id, dtype: float64