In [1]:
import pandas as pd

In [8]:
%pip install openpyxl

Requirement already satisfied: openpyxl in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from openpyxl) (2.0.0)
Note: you may need to restart the kernel to use updated packages.

In [9]:

order_process_raw = pd.read_excel("/Users/mangchinpar/Desktop/DA File/Muesli-Project-Group3-/data/Muesli Project raw data.xlsx", sheet_name='Order Process Data')
order_process_raw.head()

   Row ID        Order ID Order Date On Truck Scan Date            Ship Mode
0    3074  CA-2019-125206 2019-01-03         2019-01-07              Express
1    4919  CA-2019-160304 2019-01-02         2019-01-09  Standard Processing
2    4920  CA-2019-160304 2019-01-02         2019-01-09  Standard Processing
3    8604  US-2019-116365 2019-01-03         2019-01-09  Standard Processing
4    8605  US-2019-116365 2019-01-03         2019-01-09  Standard Processing

In [4]:
order_process_raw.head()

   Row ID        Order ID Order Date On Truck Scan Date            Ship Mode
0    3074  CA-2019-125206 2019-01-03         2019-01-07              Express
1    4919  CA-2019-160304 2019-01-02         2019-01-09  Standard Processing
2    4920  CA-2019-160304 2019-01-02         2019-01-09  Standard Processing
3    8604  US-2019-116365 2019-01-03         2019-01-09  Standard Processing
4    8605  US-2019-116365 2019-01-03         2019-01-09  Standard Processing

In [5]:
order_process_raw.shape

(5899, 5)

In [6]:
order_process_raw.info()

<class 'pandas.DataFrame'>
RangeIndex: 5899 entries, 0 to 5898
Data columns (total 5 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Row ID              5899 non-null   int64
 1   Order ID            5899 non-null   str
 2   Order Date          5899 non-null   datetime64[us]
 3   On Truck Scan Date  5899 non-null   datetime64[us]
 4   Ship Mode           5899 non-null   str
dtypes: datetime64[us](2), int64(1), str(2)
memory usage: 230.6 KB

In [7]:
order_process_raw.isnull().sum()

Row ID                0
Order ID              0
Order Date            0
On Truck Scan Date    0
Ship Mode             0
dtype: int64

In [10]:
order_process_raw.duplicated().sum()

np.int64(0)

In [11]:
order_process_raw.columns = (
    order_process_raw.columns
    .str.strip()
    .str.lower()
    .str.replace(' ', '_')
    .str.replace('/', '_')
    .str.replace('-', '_')
)

order_process_raw.head()

   row_id        order_id order_date on_truck_scan_date            ship_mode
0    3074  CA-2019-125206 2019-01-03         2019-01-07              Express
1    4919  CA-2019-160304 2019-01-02         2019-01-09  Standard Processing
2    4920  CA-2019-160304 2019-01-02         2019-01-09  Standard Processing
3    8604  US-2019-116365 2019-01-03         2019-01-09  Standard Processing
4    8605  US-2019-116365 2019-01-03         2019-01-09  Standard Processing